// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_zw8R0sgQh5aB34RKxKShVZ6VT7WZRI',
    appId: '1:339985182456:web:4e97c308441f8011b2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    authDomain: 'qourz-5daa5.firebaseapp.com',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
    measurementId: 'G-X3WF5B9GL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLqKRpSkztyU2JyUyoKwKZzEWWaeAY9s',
    appId: '1:339985182456:android:ca3aa16344c7bf95b2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHvTnUJ12s2DJlGwD-PGbYtdZ1-elxvWo',
    appId: '1:339985182456:ios:fe5bf6d396e433bcb2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
    iosBundleId: 'com.app.qoruz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHvTnUJ12s2DJlGwD-PGbYtdZ1-elxvWo',
    appId: '1:339985182456:ios:fe5bf6d396e433bcb2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
    iosBundleId: 'com.app.qoruz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9_zw8R0sgQh5aB34RKxKShVZ6VT7WZRI',
    appId: '1:339985182456:web:7fd2dacaf9b63be9b2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    authDomain: 'qourz-5daa5.firebaseapp.com',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
    measurementId: 'G-F8MPZ2HY0J',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA9_zw8R0sgQh5aB34RKxKShVZ6VT7WZRI',
    appId: '1:339985182456:web:2548c86d7fd3b822b2150d',
    messagingSenderId: '339985182456',
    projectId: 'qourz-5daa5',
    authDomain: 'qourz-5daa5.firebaseapp.com',
    storageBucket: 'qourz-5daa5.firebasestorage.app',
    measurementId: 'G-406NMXHQQD',
  );
}
